name: Generate Stats Images
on:
  schedule: [{ cron: "0 0 * * *" }] # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: absabur
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Dhaka
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_isocalendar: yes # This replaces the Streak stats
